# Generated by Django 3.1.1 on 2020-10-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('var1', models.IntegerField(default=0)),
                ('var2', models.IntegerField(default=0)),
                ('var3', models.IntegerField(default=0)),
                ('var4', models.IntegerField(default=0)),
                ('var5', models.IntegerField(default=0)),
                ('var6', models.IntegerField(default=0)),
                ('var7', models.IntegerField(default=0)),
                ('var8', models.IntegerField(default=0)),
                ('var9', models.IntegerField(default=0)),
                ('var10', models.IntegerField(default=0)),
                ('var11', models.IntegerField(default=0)),
                ('var12', models.IntegerField(default=0)),
                ('input_date', models.DateTimeField(verbose_name='Date Entered')),
                ('comments', models.TextField(blank=True, default=None)),
            ],
        ),
    ]
